### ISSUE TITLE
Error during importing point_pillars package in Jupyter Notebook on M1 macOS

### ISSUE THREAD

**Issue by raghuboppana** [ika-rwth-aachen/acdc-notebooks#4]
Hi
I have installed the point_pillars package by running the below command on the mini forge virtual environment in my mac M1.

pip install git+https://github.com/ika-rwth-aachen/PointPillars.git

After the installation, I tried importing point_pillars but I am facing the below error. 

<img width="1050" alt="Screenshot 2022-12-12 at 7 35 40 PM" src="https://user-images.githubusercontent.com/104641213/207640756-232e3d31-8965-4835-ba2b-d6e83a467f08.png">

I even tried the pip install with --no-binary but still the error persists. kindly support

Thanks and Regards

Raghu Boppana

Related to [Sensor Data Processing II / Object Detection - Tasks - Training Pipeline (Jupyter Notebook)](https://courses.edx.org/courses/course-v1:RWTHx+ACDC+3T2022/jump_to/block-v1:RWTHx+ACDC+3T2022+type@vertical+block@a2ee526302f043318ee18f17a6b0e51b)

**Comment by TillBeemelmanns** [comment]
We are working on this problem and one of our colleagues it trying to figure out a workaround.

**Comment by Mayakshanesht** [comment]
Hi,
    As we have mentioned earlier, there are certain notebooks which might not run on Mac-Os. In this situation, we highly recommend to run the concerned notebook inside the cloud-based notebook environment like Google Colab. We have added the instructions, on how you can set up the Google colab environment to solve the exercises in the ACDC MOOC.
The link to the instruction page:
https://github.com/ika-rwth-aachen/acdc/wiki/Setup-JupyterLab-Coding-Environment-with-Google-Colab#import-the-widget-to-visualize-the-plots-in-the-colab-environment

Let us know, if you face any difficulty running the notebook inside the colab environment. We encourage editing the file paths with caution to get the desired results.

Thanks and Regards,
Mayur
