### ISSUE TITLE
Outdated rospy-reference

### ISSUE THREAD

**Issue by AndreasPlt** [ika-rwth-aachen/acdc-notebooks#8]
In `section_1_introduction_and_tools/3_introduction_to_ros1.ipynb`, the link to the publisher/subscriber implementation in `rospy` is outdated (see [here](https://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber)). Instead, [this link](https://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28python%29) refers to the correct website.

**Comment by TillBeemelmanns** [comment]
Hi,

thanks for pointing that out. The link has probably changed over time. 
Fixed with https://github.com/ika-rwth-aachen/acdc-notebooks/commit/10f0c8219a30346ddd9f8cf2170045de928d2e86

Best,
Till
